### ISSUE TITLE
Allow running against all rooms.

### ISSUE THREAD

**Issue by erikjohnston** [erikjohnston/synapse-find-unreferenced-state-groups#1]

**Comment by richvdh** [comment]
It seems to work fine against all rooms to me?

**Comment by MurzNN** [comment]
Can you please describe, how it works against all rooms for you? If you not specify a room id via `-r` argument, or via some other way?

**Comment by MurzNN** [comment]
Ow, seems already yes, regarding to readme:
```
This tool scans the table (optionally limiting to a room) and finds such unreferenced groups.
```

**Comment by erikjohnston** [comment]
Huh, I wonder why I thought it didn't...
